system:
    device: auto

data:
    dataset_name: huggan/smithsonian_butterflies_subset
    image_size: 128
    batch_size: 16

model:
    image_size: ${data.image_size}

algorithm:
    learning_rate: 1e-3
    weight_decay: 1e-6
    epochs: 5